package chatbot.view;

import java.awt.Color;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SpringLayout;

import chatbot.controller.ChatbotAppController;

public class ChatbotPanel extends JPanel
{
	private ChatbotAppController baseController;
	/**
	 * Initialize the sampleButton
	 */
	private JButton sampleButton;
	/**
	 * Initialize the sampleField
	 */
	private JTextField sampleField;
	
	private SpringLayout baseLayout;
	/**
	 * Constructor for the ChatbotPanel
	 * @param baseController
	 */
	public ChatbotPanel(ChatbotAppController baseController) 
	{
		this.baseController = baseController;
		sampleButton = new JButton("Click me!");
		sampleField = new JTextField(25);
		
		baseLayout = new SpringLayout();

		
		setupPanel();
		setupLayout();
		setupListeners();
	}
	/**
	 * Sets up the basic look of the Panel.
	 */
	private void setupPanel()
	{
		this.setBackground(Color.MAGENTA);
		this.setLayout(baseLayout);
		
		this.add(sampleButton);
		this.add(sampleField);
	}
	/**
	 * Dumping ground of autogenerated code. Contains the locations of items in panel.
	 */
	private void setupLayout()
	{
		baseLayout.putConstraint(SpringLayout.NORTH, sampleButton, -1, SpringLayout.NORTH, sampleField);
		baseLayout.putConstraint(SpringLayout.EAST, sampleButton, 0, SpringLayout.WEST, sampleField);
		baseLayout.putConstraint(SpringLayout.NORTH, sampleField, 33, SpringLayout.NORTH, this);
		baseLayout.putConstraint(SpringLayout.EAST, sampleField, -10, SpringLayout.EAST, this);
	}
	
	private void setupListeners()
	{
		
	}
}
